name: Sync Fork

on:
  # 每小时第 6h 检查一次
  schedule:
    - cron: '17 */6 * * *'

  # 允许手动运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork with upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/merge-upstream \
            -f branch=main
